RECORD_ON_BOOT true
USE_ENABLE_PIN false
MIC_GAIN 200
USE_HIGH_PASS_FILTER false
HIGH_PASS_CUTOFF_FREQ 200
USE_LOW_PASS_FILTER false
LOW_PASS_CUTOFF_FREQ 8000
SAMPLE_RATE 44100
BUFFER_SIZE 256
MONO_RECORD false
FILE_INDEX 1
RECORD_FOLDER
RECORD_PREFIX rec
DELETE_ON_TRIPLE_ARM false
MAX_RECORD_DURATION 300
USE_UART_MSP false
MSP_UART_ID 1
MSP_BAUD_RATE 115200
MSP_ENABLE_CHANNEL 5
MSP_CHANNEL_RANGE_MIN 1700
MSP_CHANNEL_RANGE_MAX 2100
MSP_LIPO_MIN_MV 3000
TELEMETRY_ITEMS 1
